In [1]:
import pandas as pd
import numpy as np

In [2]:
# Criando um range de datas
datas = pd.date_range('20230101', periods=6)
# Criando DataFrame
df = pd.DataFrame(np.random.randn(6, 4), index=datas, columns=["var_a", "var_b", "var_c", "var_d"])

In [3]:
df

var_a     var_b     var_c     var_d
2023-01-01  1.392085  0.439291  1.301958 -2.259827
2023-01-02  1.630815 -0.314173  0.437951 -1.523596
2023-01-03 -1.160815 -0.169719 -1.858696 -0.894423
2023-01-04 -0.527176 -0.917455 -0.484494 -0.379721
2023-01-05 -0.665941 -0.570996  0.720601 -0.897011
2023-01-06 -0.018806 -0.340936  0.333424 -0.299014

In [5]:
# Realizando transposição de dados
dft = df.T
dft

2023-01-01  2023-01-02  2023-01-03  2023-01-04  2023-01-05  2023-01-06
var_a    1.392085    1.630815   -1.160815   -0.527176   -0.665941   -0.018806
var_b    0.439291   -0.314173   -0.169719   -0.917455   -0.570996   -0.340936
var_c    1.301958    0.437951   -1.858696   -0.484494    0.720601    0.333424
var_d   -2.259827   -1.523596   -0.894423   -0.379721   -0.897011   -0.299014

In [6]:
# Extraindo valores
dft.values

array([[ 1.39208488,  1.63081527, -1.16081533, -0.52717636, -0.66594142,
        -0.01880569],
       [ 0.43929126, -0.31417312, -0.16971897, -0.91745507, -0.57099584,
        -0.34093607],
       [ 1.3019578 ,  0.43795141, -1.85869558, -0.48449444,  0.72060092,
         0.33342382],
       [-2.25982743, -1.52359563, -0.89442277, -0.37972052, -0.89701136,
        -0.29901367]])

In [7]:
# Tamanho
np.size(dft.values)

24

In [8]:
# Executando reshape
v = dft.values
v

array([[ 1.39208488,  1.63081527, -1.16081533, -0.52717636, -0.66594142,
        -0.01880569],
       [ 0.43929126, -0.31417312, -0.16971897, -0.91745507, -0.57099584,
        -0.34093607],
       [ 1.3019578 ,  0.43795141, -1.85869558, -0.48449444,  0.72060092,
         0.33342382],
       [-2.25982743, -1.52359563, -0.89442277, -0.37972052, -0.89701136,
        -0.29901367]])

In [9]:
v.reshape(2,12)

array([[ 1.39208488,  1.63081527, -1.16081533, -0.52717636, -0.66594142,
        -0.01880569,  0.43929126, -0.31417312, -0.16971897, -0.91745507,
        -0.57099584, -0.34093607],
       [ 1.3019578 ,  0.43795141, -1.85869558, -0.48449444,  0.72060092,
         0.33342382, -2.25982743, -1.52359563, -0.89442277, -0.37972052,
        -0.89701136, -0.29901367]])